-- Database schema for AFIS (AI-Powered Financial Intelligence System)

-- 1. Transactions Table (ledger records)
CREATE TABLE IF NOT EXISTS transactions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    date TEXT NOT NULL,          -- Format: YYYY-MM-DD
    category TEXT NOT NULL,
    description TEXT,
    type TEXT NOT NULL CHECK(type IN ('income', 'expense')),
    amount REAL NOT NULL CHECK(amount >= 0)
);

-- 2. Forecasts Table (generated by ML forecasting engine)
CREATE TABLE IF NOT EXISTS forecasts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    date TEXT NOT NULL,          -- Format: YYYY-MM
    predicted_income REAL NOT NULL,
    predicted_expense REAL NOT NULL,
    confidence_lower REAL NOT NULL,
    confidence_upper REAL NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. Governance Audit Logs (aligned with NIST AI RMF 1.0)
CREATE TABLE IF NOT EXISTS audit_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    level TEXT NOT NULL CHECK(level IN ('INFO', 'WARNING', 'ERROR')),
    module TEXT NOT NULL,        -- ETL, ML_MODEL, AI_AGENT
    message TEXT NOT NULL,
    details TEXT                 -- JSON string or text for details
);

-- 4. LLM Response Cache (Epic 4 — Token Efficiency)
-- Stores hashed prompt → response pairs to avoid duplicate API calls.
-- TTL: 24 hours. Entries older than 86400 seconds are considered stale.
CREATE TABLE IF NOT EXISTS llm_cache (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    prompt_hash TEXT NOT NULL UNIQUE,  -- SHA-256 hex of the full prompt string
    response_json TEXT NOT NULL,       -- Minified JSON string returned by LLM
    model TEXT NOT NULL,               -- Model identifier (e.g. claude-haiku-4-5-20251001)
    tokens_used INTEGER DEFAULT 0,     -- Total tokens consumed (input + output)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
