-- Database schema for AFIS (AI-Powered Financial Intelligence System)

-- 1. Transactions Table (ledger records)
CREATE TABLE IF NOT EXISTS transactions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    date TEXT NOT NULL,          -- Format: YYYY-MM-DD
    category TEXT NOT NULL,
    description TEXT,
    type TEXT NOT NULL CHECK(type IN ('income', 'expense')),
    amount REAL NOT NULL CHECK(amount >= 0)
);

-- 2. Forecasts Table (generated by ML forecasting engine)
CREATE TABLE IF NOT EXISTS forecasts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    date TEXT NOT NULL,          -- Format: YYYY-MM
    predicted_income REAL NOT NULL,
    predicted_expense REAL NOT NULL,
    confidence_lower REAL NOT NULL,
    confidence_upper REAL NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. Compliance & Audit Logs (aligned with NIST AI RMF 1.0)
CREATE TABLE IF NOT EXISTS compliance_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    level TEXT NOT NULL CHECK(level IN ('INFO', 'WARNING', 'ERROR')),
    module TEXT NOT NULL,        -- ETL, ML_MODEL, AI_AGENT
    message TEXT NOT NULL,
    details TEXT                 -- JSON string or text for details
);
